### ISSUE TITLE
Some weirdness with plot_recent_fac_increases

### ISSUE THREAD

**Issue by nmmarquez** [uclalawcovid19behindbars/behindbarstools#61]
@erika-tyagi @hjohns12 any idea on what might be happening here I ran the following code for immigration data and recent facility increases and got some surprising results. No rush on this but flagging for a later discussion.

```
rm(list=ls())
library(tidyverse)
library(behindbarstools)

# get immigration data for all dates not just latest
imm_df <- read_scrape_data(all_dates = TRUE) %>%
    filter(Jurisdiction == "immigration")

# for some reason produces 3 ts lines???
plot_recent_fac_increases(imm_df, num_fac = 2)
# for some reason produces 5 ts lines that have weird dropes im not seeing in the data
# also maybe indicates that a recent increase caught here wasnt caught in the first plot
plot_recent_fac_increases(imm_df, num_fac = 3)
```

![c1b4c424-d1df-4f46-8ecf-d9da75db928c](https://user-images.githubusercontent.com/5198764/105275460-68a2e180-5b6d-11eb-924c-cbdb5e8d32d9.png)

![19108e7a-f379-4971-83cb-d2d331c69509](https://user-images.githubusercontent.com/5198764/105275465-6cceff00-5b6d-11eb-801a-6d2dabffe1d5.png)

**Comment by erika-tyagi** [comment]
The bug is that there isn't a tie-breaker in selecting the top n facilities. 

Bergen and Houston tied for second, so `num_fac = 2` grabbed both facilities (3 in total) in the first. I'll create an issue for that. Thoughts on what the tie-breaker should be? Highest current value of the metric, then Name maybe? At the very least, ties should throw a warning. 

In the second plot, I do see that drop in the raw data. I see 452 on 11/12, 158 on 11/16, and 458 on 11/17 from this: 

```
imm_df %>% 
    filter(Name == "ICE LA PALMA CORRECTIONAL CENTER") %>% 
    filter(Date > "2020-11-12" & Date < "2020-11-18") %>% 
    select(Date, Residents.Confirmed) 
```

**Comment by nmmarquez** [comment]
aah im a big dummy and was looking for the drop in the wrong date range thanks for that sanity check. Ties with warnings makes sense to me

**Comment by nmmarquez** [comment]
Closing as this looks like it is taken care of in another issue
