### ISSUE TITLE
Column order in read_scrape_data

### ISSUE THREAD

**Issue by erika-tyagi** [uclalawcovid19behindbars/behindbarstools#63]
Minor gripe: Since we dropped the long `select` statement, the variables from `read_scrap_data` are in a confusing order. 

Mainly, `source` is in the middle of all of the COVID metrics, so I can't use something like `Residents.Active:Staff.Tested` to grab them, bc I'll accidentally grab `source` too.  

This will take 2 seconds to update, but wanted to double-check if anything downstream relies on the column order. `write_latest_data` from the scrapers specifies the order explicitly, so that won't be affected.

**Comment by nmmarquez** [comment]
Nothing on my end that I can think of. I definitely do think source should be moved because that is a silly order. Is it possible to grab all the coulmns we need for COVID metrics with something like `starts_with("Residents.|Staff.")`. I'm worried something might change down the line that might mess with position but this might be equally unsafe.

**Comment by hjohns12** [comment]
I would love for us to try using the `reorder_cols` function in behindbarstools to try to achieve consistency between historical and newly scraped data. Could we update reorder_cols if need be, and stick that into `read_scrape_data`? 

https://github.com/uclalawcovid19behindbars/behindbarstools/blob/master/R/reorder_cols.R
