### ISSUE TITLE
Multiple sources of `Residents.Population` for the same day in CA?

### ISSUE THREAD

**Issue by hjohns12** [uclalawcovid19behindbars/behindbarstools#81]
Is summing the values the expected behavior in the coalesce for Residents.Population? 

```
recent_dat <- behindbarstools::read_scrape_data(all_dates = TRUE, 
                                               state = "California", 
                                              debug = TRUE)
```

Group Date: 2020-11-18, Name: FOLSOM STATE PRISON, State: California, jurisdiction_scraper: state, Facility.ID: 120 has multiple values that do not match for column Residents.Population. Only using sum of observed value from the following unique values 2136, 84

Group Date: 2020-01-01, Name: CALIFORNIA STATE PRISON SAN QUENTIN, State: California, jurisdiction_scraper: state, Facility.ID: 100 has multiple values that do not match for column Residents.Population. Only using sum of observed value from the following unique values 4157, 1

**Comment by hjohns12** [comment]
cc @erika-tyagi @nmmarquez

**Comment by erika-tyagi** [comment]
Good catch! In this case, we DO want this to be happening, but we definitely don't want the warnings. CA reports population data separately for men and women, but under the same facility name (e.g. 1/1/20 shows 4157 men and 1 woman - raw file [here](https://www.cdcr.ca.gov/research/wp-content/uploads/sites/174/2020/01/Tpop1d200101.pdf)). For the single-gender facilities, this is totally fine. For the mixed-gender facilities, we would want to sum these – so the `group_by_coalesce(.method="sum")` does indeed give us the correct total population of a facility for a date. I should've noticed this earlier though, my bad! 

A few options I can think of: 
1. Re-do the historical scrape but add a facility name group/sum in the scraper code itself (rather than here). 
2. Pull and report separate population data for men and women, and then deal with aggregation via (yet another) crosswalk (i.e. like with the federal vaccine data) after scraping but before `read_scrape_data()`-ing.  
3. Ignore `group_by_coalesce` warnings for `Residents.Population` in `read_scrape_data()`. 

Facility aggregation mismatches will generally be a problem when integrating population data , and I'm going to need help figuring out what we as a team want to do. So here: warnings = bad, behavior = good. In general: 🆘.

**Comment by hjohns12** [comment]
Hmmmmmmmmmmm

I don't know what's best! I feel apprehensive about option #3. As we integrate more historical population and historical COVID data, might there be a situation when that warning is helpful? 

Option #2 seems the most work-intensive. If we're planning to create a federal data facility-to-sub-facility map, though, part of me wonders if we should expand this to other, similar, situations. Not helpful in the short-term, though! 

What is your instinct @erika-tyagi ?

**Comment by erika-tyagi** [comment]
> Hmmmmmmmmmmm
> 
> I don't know what's best! I feel apprehensive about option #3. As we integrate more historical population and historical COVID data, might there be a situation when that warning is helpful?
> 
> Option #2 seems the most work-intensive. If we're planning to create a federal data facility-to-sub-facility map, though, part of me wonders if we should expand this to other, similar, situations. Not helpful in the short-term, though!
> 
> What is your instinct @erika-tyagi ?

I think my initial instinct is to go with 1 for now, and then work through another few states and see if 2 or 3 make more sense longer-term given how population data tends to be reported? Idk, I might think about this a little more and then set up time with you / Neal to talk through options for pipelines!

**Comment by nmmarquez** [comment]
I also like the sound of option 1 here but defer to you Erika as you are the one who is mostly extracting this information and have the best idea of what is sensible. Also happy to sit and talk about it

**Comment by hjohns12** [comment]
Makes sense to me, and I'm down to discuss more if that's helpful whenever!

**Comment by erika-tyagi** [comment]
All fixed with option 1 with no more coalesce warnings! 

Still thinking about a longer-term solution, but considering either (1) leveraging `fac_spellings` or (2) having a separate population names crosswalk that's used to handle the grouping and aggregation at the extraction stage within the scrapers.

**Comment by hjohns12** [comment]
I wonder if measures for justice or vera has thought about what to do about this issue. Could be helpful to discuss (although I know our pipeline is very, very different from MFJ's). Will be good to discuss pros and cons of the various options as a group!

**Comment by erika-tyagi** [comment]
> I wonder if measures for justice or vera has thought about what to do about this issue. Could be helpful to discuss (although I know our pipeline is very, very different from MFJ's). Will be good to discuss pros and cons of the various options as a group!

That's a good point! I think MFJ and Vera never aggregate at at a level more granular than the county-level, which makes things a lot more straightforward! Still thinking about general and flexible solutions, but closing this for now!
